version: "3.9"

services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: emp-t3
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/empdb?schema=public
    depends_on:
      - db 
    networks:
      - emp-net

  db:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=empdb
    networks:
      - emp-net
    volumes:
      - emp:/var/lib/postgresql

networks:
  emp-net:
volumes:
  emp:
